### ISSUE TITLE
Problem with recipes

### ISSUE THREAD

**Issue by jjgomezcadenas** [Moelf/FHist.jl#84]
Hello, 
Wen including FHist in my Pluto notebook, 
````
begin
	import PlutoUI
	using FHist
	using Printf
	using Plots
end
````
it returns an error:

```
LoadError: MethodError: no method matching var"@recipe"(::LineNumberNode, ::Module, ::Expr)

Closest candidates are:

var"@recipe"(::LineNumberNode, ::Module, ::Any, !Matched::Symbol, !Matched::Symbol...)

@ MakieCore ~/.julia/packages/MakieCore/zgrOY/src/recipes.jl:167

in expression starting at /Users/jjgomezcadenas/.julia/packages/FHist/N3dfh/src/plots.jl:3

in expression starting at /Users/jjgomezcadenas/.julia/packages/FHist/N3dfh/src/plots.jl:3

include(::Module, ::String)@Base.jl:457
include(::String)@FHist.jl:1
top-level scope@Requires.jl:40
eval@boot.jl:370[inlined]
eval@FHist.jl:1[inlined]
(::FHist.var"#101#110")()@require.jl:101
macro expansion@timing.jl:393[inlined]
err(::Any, ::Module, ::String, ::String, ::Any)@require.jl:47
(::FHist.var"#100#109")()@require.jl:100
withpath(::Any, ::String)@require.jl:37
(::FHist.var"#99#108")()@require.jl:99
#invokelatest#2@essentials.jl:819[inlined]
invokelatest@essentials.jl:816[inlined]
foreach(::typeof(invokelatest), ::Vector{Function})@abstractarray.jl:3075
loadpkg(::Base.PkgId)@require.jl:27
#invokelatest#2@essentials.jl:819[inlined]
invokelatest@essentials.jl:816[inlined]
run_package_callbacks(::Base.PkgId)@loading.jl:1129
_require_prelocked(::Base.PkgId, ::String)@loading.jl:1667
macro expansion@loading.jl:1648[inlined]
macro expansion@lock.jl:267[inlined]
require(::Module, ::Symbol)@loading.jl:1611
top-level scope@[Other: 5](http://localhost:1235/edit?id=a4eb16cc-53e4-11ee-2791-87b16b34de44#)
````
Then I try a simple example:

```
a = randn(10000);
h1 = Hist1D(a, -4:0.1:4)
plot(h1)
```

which fails:

```
Cannot convert FHist.Hist1D{Int64, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}} to series data for plotting

error(::String)@error.jl:35
_prepare_series_data(::FHist.Hist1D{Int64, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}})@series.jl:8
_series_data_vector(::FHist.Hist1D{Int64, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}, ::Dict{Symbol, Any})@series.jl:36
macro expansion@series.jl:129[inlined]
apply_recipe(::AbstractDict{Symbol, Any}, ::Type{RecipesPipeline.SliceIt}, ::Any, ::Any, ::Any)@RecipesBase.jl:300
_process_userrecipes!(::Any, ::Any, ::Any)@user_recipe.jl:38
recipe_pipeline!(::Any, ::Any, ::Any)@RecipesPipeline.jl:72
_plot!(::Plots.Plot, ::Any, ::Any)@plot.jl:223
#plot#188@plot.jl:102[inlined]
plot@plot.jl:93[inlined]
top-level scope@[Local: 1](http://localhost:1235/edit?id=a4eb16cc-53e4-11ee-2791-87b16b34de44#)[inlined]
```

I can still plot this histogram (sending to plot the weights and the centers) but the direct recipe seems to fail. 

Thanks for an excellent package!

**Comment by Moelf** [comment]
do you still see this if you run it in REPL? I don't trust Pluto.jl sometimes

**Comment by Moelf** [comment]
you can file an issue in Pluto.jl and see what they say. I suspect it may be have something to do with Requires.jl which we use:
https://github.com/Moelf/FHist.jl/blob/8064f873ce561023dae1cdfa354e268dc88c16a9/src/FHist.jl#L45-L48

if the Julia you guys use is new enough, you can make a PR to use the new weak deps: https://github.com/SciML/DiffEqBase.jl/pull/856 and I will happily accept the PR

**Comment by jjgomezcadenas** [comment]
Hi Thanks! I will put an Issue in Pluto. We use a very new version of Julia, but not sure about how to proceed regarding your second comment:

``if the Julia you guys use is new enough, you can make a PR to use the new weak deps: https://github.com/SciML/DiffEqBase.jl/pull/856 and I will happily accept the PR``

**Comment by Moelf** [comment]
I'm just saying I would welcome a PR to this repo that removes migrate Requires.jl usage to use the now built-in extensions facility of Julia.

**Comment by jjgomezcadenas** [comment]
Hello again, I have tried to follow the examples and submitted at PR with the relevant changes.

**Comment by Moelf** [comment]
is this fixed now?

**Comment by jjgomezcadenas** [comment]
Not fixed yet, I'm afraid. What I did:

1. I rebased my main branch to the main in your branch.
2. Prepare a test repo (https://github.com/jjgomezcadenas/MathTools.jl)
3. Made that test repo dependent of FHist (e.g, my local repo which is sync with your main branch)
4. Run the pluto notebook you can find in the "nb" directory.
5. I get errors when try to use CairoMakie
```
LoadError: MethodError: no method matching var"@recipe"(::LineNumberNode, ::Module, ::Expr, ::Symbol)

Closest candidates are:

var"@recipe"(::LineNumberNode, ::Module, ::Expr)

@ RecipesBase ~/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:267

in expression starting at /Users/jjgomezcadenas/.julia/packages/FHist/a1vSI/src/makie.jl:32

in expression starting at /Users/jjgomezcadenas/.julia/packages/FHist/a1vSI/src/makie.jl:32

#macroexpand#63@expr.jl:119[inlined]
macroexpand@expr.jl:117[inlined]
docm(::LineNumberNode, ::Module, ::Any, ::Any, ::Bool)@Docs.jl:539
docm(::LineNumberNode, ::Module, ::Any, ::Any)@Docs.jl:539
(::DocStringExtensions.var"#35#36"{typeof(DocStringExtensions.template_hook)})(::LineNumberNode, ::Vararg{Any})@templates.jl:11
var"@doc"(::LineNumberNode, ::Module, ::String, ::Vararg{Any})@boot.jl:539
include(::Module, ::String)@Base.jl:457
include(::String)@FHist.jl:1
top-level scope@Requires.jl:40
eval@boot.jl:370[inlined]
eval@FHist.jl:1[inlined]
(::FHist.var"#106#115")()@require.jl:101
macro expansion@timing.jl:393[inlined]
err(::Any, ::Module, ::String, ::String, ::Any)@require.jl:47
(::FHist.var"#105#114")()@require.jl:100
withpath(::Any, ::String)@require.jl:37
(::FHist.var"#104#113")()@require.jl:99
#invokelatest#2@essentials.jl:819[inlined]
invokelatest@essentials.jl:816[inlined]
foreach(::typeof(invokelatest), ::Vector{Function})@abstractarray.jl:3075
loadpkg(::Base.PkgId)@require.jl:27
#invokelatest#2@essentials.jl:819[inlined]
invokelatest@essentials.jl:816[inlined]
run_package_callbacks(::Base.PkgId)@loading.jl:1129
_tryrequire_from_serialized(::Base.PkgId, ::String, ::String, ::String, ::Vector{Any})@loading.jl:1398
_require_search_from_serialized(::Base.PkgId, ::String, ::UInt128)@loading.jl:1494
_require(::Base.PkgId, ::String)@loading.jl:1783
_require_prelocked(::Base.PkgId, ::String)@loading.jl:1660
macro expansion@loading.jl:1648[inlined]
macro expansion@lock.jl:267[inlined]
require(::Module, ::Symbol)@loading.jl:1611
top-level scope@[Other: 1](http://localhost:1234/edit?id=06b154a6-8b04-11ee-3efb-e100d2147193#)
````

So the Makie part doesn't seem to work.

**Comment by Moelf** [comment]
That's not Makie, recipeBase is Plots.jl

**Comment by jjgomezcadenas** [comment]
It's strange because the nb works for Plots.

**Comment by Moelf** [comment]
Can you make a PR to put Plots.jl Pluto notebook in the doc notebook folder? We should probably include those examples in doc anyway

**Comment by jjgomezcadenas** [comment]
Yes, the only reason I didn't do it already is that is not clear to me how you call Pluto from the doc folder,  not familiar with this structure, can you let me know?

**Comment by Moelf** [comment]
You can make a PR to just add the .jl Pluto file, I will make it work don't worry. It's mostly automated in the build.jl and make.jl file inside the ./docs

**Comment by jjgomezcadenas** [comment]
OK, will do (tomorrow)

**Comment by Moelf** [comment]
Fixed in #92
